@startuml
namespace weekly {
class  WeeklyScreen {
   + workoutViewModel: WorkoutViewModel = viewModel(),
}
namespace components {
    class WeekEntry {
            + weekDay: DaysInWeek,
            + workouts: List<Workout>,
            + allWorkouts: List<Workout>,
            + onWorkoutAssign: (Workout) -> Unit,
            + onWorkoutEntryDelete: (Workout) -> Unit,

    }

    class WorkoutEntry {
        + weekDay: DaysInWeek,
        + workout: Workout,
        + onWorkoutEntryDelete: (Workout) -> Unit,
    }

    class AssignWorkoutDialog {
          +  weekName: DaysInWeek,
           + workouts: List<Workout>,
            + onClose: () -> Unit,
            + modifier: Modifier = Modifier,
            + onAddAction: (Workout) -> Unit = {},

    }

    class DeleteConfirmationDialog {
    + onDeleteConfirm: () -> Unit,
    + onDeleteCancel: () -> Unit,
    + modifier: Modifier = Modifier
    }

    class NoWorkoutEntryVariant {
       + allWorkouts: List<Workout>,
        +    weekDay: DaysInWeek,
         +   onWorkoutAssign: (Workout) -> Unit

    }

    class WorkoutDetailDialog {

   +     weekDay: DaysInWeek,
   +     workout: Workout,
    +    onClose: () -> Unit,
     +   modifier: Modifier = Modifier,
    }

}
}



WeeklyScreen ..> WeekEntry
WeeklyScreen ..> datasource
WeeklyScreen ..> ui.components
WeeklyScreen ..> models.Workout

WeekEntry ..> WorkoutEntry
WeekEntry ..> NoWorkoutEntryVariant

WorkoutEntry ..> DeleteConfirmationDialog
WorkoutEntry ..> WorkoutDetailDialog

NoWorkoutEntryVariant ..> AssignWorkoutDialog

@enduml